default_platform(:ios)

platform :ios do
  desc "Build and upload iOS app to App Store Connect"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      in_house: false
    )

    build_app(
      project: "SDOMultiplatform/iosApp/iosApp.xcodeproj",
      scheme: "iosApp",
      configuration: "Release",
      export_method: "app-store",
      export_options: {
        compileBitcode: true,
        uploadBitcode: true,
        uploadSymbols: true
      }
    )

    upload_to_app_store(
      api_key: api_key
    )
  end
end